### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Dare-Devill** [14sept2002/Kunai#2]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Kunai/kunai.py", line 16, in <module>
    i = InstagramUser(uname)
        ^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/instagramy/InstagramUser.py", line 63, in __init__
    username, data["entry_data"]["ProfilePage"][0]["graphql"]["user"]
              ~~~~^^^^^^^^^^^^^^
KeyError: 'entry_data'

**Comment by TYT-Abhi** [comment]
Here to 😔
